package pt.isel.reversi.cli

import pt.isel.reversi.utils.CLI_CONFIG_FILE
import pt.isel.reversi.utils.ConfigLoader

val CONFIG: CliConfig = ConfigLoader(CLI_CONFIG_FILE) { CliConfig(it) }.loadConfig()

val WELCOME_MESSAGE = CONFIG.WELCOME_MESSAGE
val PROMPT = CONFIG.PROMPT
val PROMPT_COLOR = CONFIG.PROMPT_COLOR
val TEXT_COLOR = CONFIG.TEXT_COLOR
val ERROR_COLOR = CONFIG.ERROR_COLOR
val WARNING_COLOR = CONFIG.WARNING_COLOR
val INFO_COLOR = CONFIG.INFO_COLOR
val HELP_USAGE_COLOR = CONFIG.HELP_USAGE_COLOR
val HELP_ALIAS_COLOR = CONFIG.HELP_ALIAS_COLOR
val HELP_DESC_COLOR = CONFIG.HELP_DESC_COLOR
